### ISSUE TITLE
Doesn't work in IOS 11

### ISSUE THREAD

**Issue by sudheerg9** [guyromb/Cordova-open-native-settings#18]
Cordova native settings is not working properly on IOS 11. When we call any of the page. It is just opening default/general settings page or taking us to previously opened settings page.  Cam anyone have a solution for this?

**Comment by hannibaldinski** [comment]
Same problem here and Android 8.x seems to have the same issues.

**Comment by gregor-srdic** [comment]
I am also seeing this problem on iOS 11.1 :S

**Comment by VaveAdmin** [comment]
Same here, any update?

**Comment by AramVave** [comment]
Same here. Any update?

**Comment by hannibaldinski** [comment]
From looking around, no one really knows how to fix it. iOS never supported it officially I think.

**Comment by guyromb** [comment]
Under investigation. As mentioned previously, it was never officially supported by iOS.
If anyone find a solution please update here.

**Comment by Aa22041100** [comment]
Same here.
Any update?

**Comment by hannibaldinski** [comment]
@MZabih What do you mean with "my app logs me out"?

**Comment by guyromb** [comment]
iOS 11 fix merged

**Comment by grinmax** [comment]
What about IOS 12?

**Comment by luigi37** [comment]
Hi all, same issue here. On iOS 12 both simulator and real device (iphone 5S) it opens  just general settings

**Comment by ppappukim** [comment]
same issue here. it doesn't work in IOS 13 ~

**Comment by Hanzofm** [comment]
Same on iOS 14 and android newer versions
