### ISSUE TITLE
Possible to add "Notification" ?

### ISSUE THREAD

**Issue by luigi37** [guyromb/Cordova-open-native-settings#19]
Hi, thanks for this plugin.
Would be possible to add "application_notifications" to the ANDROID options?
I'd need to point my user to change some application notification options.
So far the closest I found is "application_details" but a further click is required to  see "Notifications"
Thanks

**Comment by luigi37** [comment]
BTW: it seems here there is a way but I was not able to implement it in the plugin:

**Comment by guyromb** [comment]
@luigi37 what are you struggling with the implementation?

**Comment by luigi37** [comment]
I tried all the options suggested at the link above but I could not manage to make the plugin compile properly... unfortunately my knowledge of Java/Android is quite poor...

**Comment by luigi37** [comment]
Any chance that the code for notification will be added in future? Thanks

**Comment by luigi37** [comment]
Sorry to push.... any chance that the "Notification" window could be opened directly in Android (and eventually on iOS? I tried again to add the code myself but no luck...

**Comment by guyromb** [comment]
Can you send your modifications so I can review it?
What error do you get?

**Comment by guyromb** [comment]
https://github.com/guyromb/Cordova-open-native-settings/pull/22
does it solve you issue?

**Comment by luigi37** [comment]
Thank you. I will try tonight and report
