### ISSUE TITLE
Class not found for android

### ISSUE THREAD

**Issue by thecodearcher** [guyromb/Cordova-open-native-settings#23]
Cordova native settings is not working properly on Android Ionic Apps. When i call any of the page. It throws an error "Class Not Found".
 Can anyone have a solution for this?

**Comment by hannibaldinski** [comment]
Which Android version?

**Comment by thecodearcher** [comment]
Android 7.0

**Comment by thecodearcher** [comment]
Found out the solution was to remove platform after installing plugin and add the android platform back
