### ISSUE TITLE
Update of release

### ISSUE THREAD

**Issue by ThorvaldAagaard** [guyromb/Cordova-open-native-settings#24]
Will you create an official 1.5.0 release.

![image](https://user-images.githubusercontent.com/10560652/35413105-b108bbbc-021e-11e8-8e73-1b9732061aab.png)

Currently github only shows an old release

**Comment by pitAlex** [comment]
Please update plugin.xml to be 1.5 also. It's still 1.4.1

**Comment by guyromb** [comment]
Everything is now aligned.
