### ISSUE TITLE
iOS: open('bluetooth') opens general settings page

### ISSUE THREAD

**Issue by bryantee** [guyromb/Cordova-open-native-settings#25]
Is bluetooth working in iOS 11? It just seems to open the general settings page for me.

```typescript
 window.cordova.plugins.settings.open('bluetooth', () => res())
```

**Comment by hannibaldinski** [comment]
Sadly opening settings on iOS 11 is broken. As it was always kind of a hack, no one has found a solution to fix it.

**Comment by guyromb** [comment]
Related issue: https://github.com/guyromb/Cordova-open-native-settings/issues/18
