### ISSUE TITLE
Wrong engines in package.json

### ISSUE THREAD

**Issue by timbru31** [guyromb/Cordova-open-native-settings#26]
The package.json defines cordova as an engine (https://github.com/guyromb/Cordova-open-native-settings/blob/master/package.json#L22-L25), the nowadays recommended way is to define cordova engines like the following:
```
"engines": {
    "cordovaDependencies": {
        PLUGIN_VERSION: {
            DEPENDENCY: SEMVER_RANGE,
            DEPENDENCY: SEMVER_RANGE,
            ...
        },
        ...
    }
}
```
For more information see https://cordova.apache.org/docs/en/7.x/guide/hybrid/plugins/index.html#specifying-cordova-dependencies

**Comment by guyromb** [comment]
@timbru31 do you mind to update it to the new structure and make a pull request? I'll gladly merge it.
thanks

**Comment by timbru31** [comment]
Yes, I'll try to do one later today. 👍

**Comment by timbru31** [comment]
Took me longer than *one* day, but I created a PR 👍

**Comment by guyromb** [comment]
Awesome @timbru31 !
