### ISSUE TITLE
Doesn't work on iOS 10

### ISSUE THREAD

**Issue by guyromb** [guyromb/Cordova-open-native-settings#3]
Native settings won't open on iOS 10.
According to some discussions in stackoverflow seems like apple disabled the option to open native settings programmatically in iOS 10 (except for app settings).

I will keep on tracking regarding this matter and do further investigation soon.

**Comment by jedofus** [comment]
I found it, but I don't know if this will help you
[http://useyourloaf.com/blog/openurl-deprecated-in-ios10/](url)

**Comment by M-arcus** [comment]
The correct link is http://useyourloaf.com/blog/openurl-deprecated-in-ios10/

**Comment by guyromb** [comment]
Fixed here
https://github.com/guyromb/Cordova-open-native-settings/pull/5
