### ISSUE TITLE
iOS app gets rejected because of use of "prefs:root" or "App-Prefs:root" private API's. 

### ISSUE THREAD

**Issue by ipehimanshu** [guyromb/Cordova-open-native-settings#36]
5.0.0 Binary Rejected Aug 31, 2018
Guideline 2.5.1 - Performance - Software Requirements Your app uses the "prefs:root=" non-public URL scheme, which is a private entity.
Here is their suggested solution:
Guideline 2.5.1 - Performance - Software Requirements

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.￼

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

So any one please help us to resolve this issue

**Comment by goinnn** [comment]
Yes I get the same. If I remove "this if" https://github.com/guyromb/Cordova-open-native-settings/blob/master/src/ios/NativeSettings.m#L20 and this config https://github.com/guyromb/Cordova-open-native-settings/blob/master/plugin.xml#L36 all works. Tested in ios9-ios11.

@guyromb please could you tell us what you think about it?

Today I am going to do a pull request

**Comment by guyromb** [comment]
PR: https://github.com/guyromb/Cordova-open-native-settings/pull/34
Need to test on iOS 10

**Comment by goinnn** [comment]
With #34 I will get the same error. iOS don't want you use prefs API. You can not have pref API in URL Types. :-(

https://forum.starling-framework.org/topic/appstore-rejection

**Comment by ipehimanshu** [comment]
so is this issue now solved?

**Comment by ipehimanshu** [comment]
if yes then can you please say which version should i installed for this plugin ?

**Comment by goinnn** [comment]
@ipehimanshu yes you can patch your plugin with this commit aa53c9112109e622b7125ce58545d7ef7af2a063 or you can install from github directly master branch

**Comment by alexhisen** [comment]
@guyromb Are you going to be publishing an updated version on npm? And what is the status of this plugin on iOS 11 - does it work?

**Comment by jasvindersingh-evon** [comment]
@guyromb: Is the app still getting rejected on Apple store?

**Comment by alexhisen** [comment]
No

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, May 30, 2019 at 12:57 AM -0700, "jasvindersingh-evon" <notifications@github.com<mailto:notifications@github.com>> wrote:


@guyromb<https://github.com/guyromb>: Is the app still getting rejected on Apple store?

-
