### ISSUE TITLE
PGB Android unable to load plugin

### ISSUE THREAD

**Issue by ppetree** [guyromb/cordova-open-native-settings#39]
Not sure what changes you've made but PGB is not able to pull your plugin from npm.  This was working. I should also add that this works with the PGB iOS builds.

    <plugin name="cordova-open-native-settings" spec="~1.5" />
    <preference name="android-build-tool" value="gradle" />
    <preference name="phonegap-version" value="cli-7.1.0" />

**"plugman-151 install --platform android --project  --plugin Cordova-open-native-settings@~1.5 --nohooks=.": Fetching plugin "Cordova-open-native-settings@~1.5" via npm
Failed to fetch plugin Cordova-open-native-settings@~1.5 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Not found : Cordova-open-native-settings**

**Comment by guyromb** [comment]
The plugin is there, version 1.5.2 -
https://www.npmjs.com/package/cordova-open-native-settings

It might be you are using `C` (capital letter) instead of `c`?

**Comment by ppetree** [comment]
Thanks for the response.

If you'll notice the plugin reference copied directly from my config.xml file... it does NOT capitalize any letters in the plugin name.  

And, again, this is building on iOS from npm.

I tried referencing the plugin with a source of "git" and using the git URL and, again, iOS built and android choked and died with the same error.

7.1.0 WAS building until you changed the version number.

**Comment by guyromb** [comment]
Let me know if you couldn't find a solution by now.
