### ISSUE TITLE
Battery Optimization

### ISSUE THREAD

**Issue by frontendDuall** [guyromb/Cordova-open-native-settings#4]
Good morning, can you open Battery Optimization?

Thank you very much

![screenshot_1](https://cloud.githubusercontent.com/assets/22939355/21986920/686d36f6-dbcf-11e6-806d-bfa847c01da2.png)

**Comment by guyromb** [comment]
The available options regarding battery for Android are:
ACTION_BATTERY_SAVER_SETTINGS
ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS

For more info check this link:
https://developer.android.com/reference/android/provider/Settings.html

**Comment by emcniece** [comment]
I have tested the `ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS` and it appears to be the page that @frontendDuall is looking for:

![Android battery optimization page](https://dl2.pushbulletusercontent.com/kPLxaVpFeUhNMJ8ExRQyKiTtRSXR5Q9W/Screenshot_20170715-114052.png)

Option parameter added in https://github.com/guyromb/Cordova-open-native-settings/pull/11

**Comment by guyromb** [comment]
@frontendDuall @emcniece Ok that's great. Can you please add it to Readme + java file and create a pull request in case you modified it already?
Thanks!

**Comment by emcniece** [comment]
@guyromb already done! https://github.com/guyromb/Cordova-open-native-settings/pull/11
