### ISSUE TITLE
Does not work with latest ionic 4

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [guyromb/cordova-open-native-settings#50]
According to https://ionicframework.com/docs/native/open-native-settings:
This does not work - If i try to import like

import { OpenNativeSettings } from '@ionic-native/open-native-settings/ngx'; this does not work as well as import { OpenNativeSettings } from '@ionic-native/open-native-settings';

**Comment by HansKrywaa** [comment]
Works for me. Make sur you have installed it correctly
