### ISSUE TITLE
Does not open settings on IOs

### ISSUE THREAD

**Issue by Victor1993** [guyromb/cordova-open-native-settings#54]
The plugin is not working on IOs, I need to open the wifi settings and it only works on android, any solution?

**Comment by ppappukim** [comment]
i have same issue in IOS 13

**Comment by Prince05true** [comment]
Having same issue. Any solution for IOS>=12

**Comment by guyromb** [comment]
Unfortunately, it's getting more and more complicated to follow the changes from Apple.
Feel free to make a PR if you find some solution :)

**Comment by J4cku** [comment]
#56

**Comment by guyromb** [comment]
A fixed is released
