### ISSUE TITLE
IOS 15 Errors

### ISSUE THREAD

**Issue by jonah-butler** [guyromb/Cordova-open-native-settings#66]
Anyone have success with IOS 15?

I import and follow the instructions per [Ionic docs](https://ionicframework.com/docs/native/open-native-settings), but whenever I visit a page that contains the OpenNativeSettings.open('settings') handler, XCode logs print:
``
⚡️  [error] - {}
⚡️  [error] - {}
⚡️  [error] - {}
``

That's unfortunately all I have to go off of at the moment.

**Comment by laurentperez** [comment]
Hi. How did you fix it ?

**Comment by jonah-butler** [comment]
I actually was not able to solve the issue with this plugin.
I was using [https://ionicframework.com/docs/native/in-app-purchase-2](url), and was not aware that IAP2 includes a method to open the manage subscriptions menu. That method is/was working for IOS 15. If you're using that package also, I would just use that.
